FROM nginx:alpine

RUN apk add --no-cache rsyslog pcre zabbix-agent2

COPY docker/nginx/rsyslog.conf /etc/rsyslog.conf
COPY docker/nginx/zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf

RUN mkdir -p /var/spool/rsyslog

COPY docker/nginx/start.sh ./

RUN chmod +x ./start.sh

EXPOSE 80

CMD [ "./start.sh" ]
