# Build stage
FROM node:18.20.6-alpine AS builder

WORKDIR /usr/src/app
COPY backend/package*.json ./
RUN npm ci
COPY backend/ ./
RUN npm run build

# Production stage
FROM node:18.20.6-alpine
RUN npm install -g pm2
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/.env ./.env
RUN npm ci --only=production && npm cache clean --force
COPY --from=builder /usr/src/app/dist ./dist
EXPOSE 3000
CMD ["pm2-runtime", "start", "dist/index.js"]
