FROM node:18.20.6-alpine AS builder

RUN npm install -g @angular/cli

WORKDIR /usr/src/app
COPY /frontend/package*.json ./
RUN npm ci
COPY /frontend/ ./
RUN npm run prod

FROM nginx:alpine

COPY --from=builder /usr/src/app/dist/frontend/browser/ /usr/share/nginx/html
COPY /docker/frontend/prod/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
